name: develop workflow test

on:
  push:
    branches: ["develop"]

env:
  tf_version: "1.5.4"
  node_version: "20.x"
  key_vault: "terraform20250909"
  secrets: "subscription-id tenant-id sp-client-id sp-client-secret nsg-inbound-ip nsg-outbound-ip"

jobs:
  Terraform_Exec:
    runs-on: [self-hosted, Linux]
    container:
      image: docker.io/library/node:iron-trixie-slim
    outputs:
      output1: ${{ steps.get_dir.outputs.tf_region_dir }}
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        tf_working_dir:
          - develop
    steps:
      - name: Setup OS
        run: |
          apt-get update && apt-get install -y ca-certificates   # イメージ初期構築時にインストールするので、実際に不要

          sed -i -e 's/http/https/' /etc/apt/sources.list.d/debian.sources
          apt-get update && apt-get install -y less vim curl unzip sudo jq git
          curl -sL https://aka.ms/InstallAzureCLIDeb | bash

      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.tf_version }}

      - name: Terraform fmt
        run: terraform fmt -recursive

      - name: Get Terraform Directory
        id: get_dir
        shell: bash
        run: |
          cd ${{ matrix.tf_working_dir }}
          echo "::set-output name=tf_region_dir::$(pwd)"

      - name: Terraform Init
        run: |
          cd ${{ matrix.tf_working_dir }}/
          terraform init -upgrade

      - name: Azure Login
        run: |
          az login --identity 1> /dev/null

      - name: Create Terraform tfvars from Key Vault
        run: |
          TFVARS_FILE=credentials.auto.tfvars
          echo "# Auto-generated from Key Vault" > $TFVARS_FILE

          for secret in ${{ env.secrets }}; do
            value=$(az keyvault secret show \
              --vault-name ${{ env.key_vault }} \
              --name "$secret" \
              --query value -o tsv)
            varname=$(echo "$secret" | tr '[:lower:]-' '[:lower:]_')
            
            echo "${varname} = \"${value}\"" >> $TFVARS_FILE

            # 機密情報はマスク
            if [[ "$varname" == "sp_client_secret" ]]; then
              echo "::add-mask::$value"
              echo "${varname} = *****"
            else
              echo "${varname} = ${value}"
            fi
          done
        shell: bash

      - name: Terraform Plan
        run: |
          cd ${{ matrix.tf_working_dir }}/
          terraform plan --parallelism=50 -no-color
