name: develop workflow test

on:
  push:
    branches: ["develop"]

env:
  tf_version: "1.5.4"
  node_version: "20.x"
  key_vault: "terraform20250909"
  provider_secrets: "subscription-id tenant-id sp-client-id sp-client-secret"
  backend_storage_account: "develop01"
  backend_container_name: "tfstate20250911"
  backend_key: "terraform.tfstate"

jobs:
  Terraform_Exec:
    runs-on: [self-hosted, Linux]
    container:
      image: docker.io/library/node:iron-trixie-slim
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        tf_working_dir:
          - develop
    steps:
      - uses: actions/checkout@v2 #リポジトリのコードをチェックアウト（取得）

      - name: Setup OS
        shell: bash
        run: |
          apt-get update && apt-get install -y ca-certificates  #イメージ初期構築時にインストールするので、実際に不要

          sed -i -e 's/http/https/' /etc/apt/sources.list.d/debian.sources
          apt-get update && apt-get install -y less vim curl unzip sudo jq git
          curl -sL https://aka.ms/InstallAzureCLIDeb | bash

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.tf_version }}

      - name: Get Terraform Directory
        id: get_dir
        shell: bash
        run: |
          cd ${{ matrix.tf_working_dir }}
          echo "tf_region_dir=$(pwd)" >> $GITHUB_OUTPUT

      - name: Terraform fmt
        run: terraform fmt -recursive

      #      - name: Azure Login
      #        shell: bash
      #        run: |
      #          az login --identity

      - name: Export Key Vault secrets as environment variables
        shell: bash
        run: |
          for secret in ${{ env.provider_secrets }}; do
            value=$(az keyvault secret show --vault-name ${{ env.key_vault }} --name "$secret" --query value -o tsv)
            name=$(echo "$secret" | tr '[:lower:]-' '[:lower:]_')
            echo "$name=$value" >> $GITHUB_ENV
          done

      - name: Generate Terraform tfvars
        shell: bash
        run: |
          TFVARS_FILE=${{ matrix.tf_working_dir }}/credentials.auto.tfvars
          echo "provider_credentials = {" > $TFVARS_FILE
          for secret in ${{ env.provider_secrets }}; do
            varname=$(echo "$secret" | tr '[:lower:]-' '[:lower:]_')
            value="${!varname}"
            echo "${varname} = \"${value}\"" >> $TFVARS_FILE
          done
          echo "}" >> $TFVARS_FILE

      - name: Terraform Init
        shell: bash
        run: |
          cd ${{ matrix.tf_working_dir }}
          terraform init -upgrade \
            -backend-config="resource_group_name=rg-tfstate" \
            -backend-config="storage_account_name=${{ env.backend_storage_account }}" \
            -backend-config="container_name=${{ env.backend_container_name }}" \
            -backend-config="key=${{ env.backend_key }}"
        # Terraformが環境変数から認証情報を取得できるように、環境変数を設定
        env:
          ARM_CLIENT_ID: ${{ env.sp_client_id }}
          ARM_CLIENT_SECRET: ${{ env.sp_client_secret }}
          ARM_TENANT_ID: ${{ env.tenant_id }}
          ARM_SUBSCRIPTION_ID: ${{ env.subscription_id }}

      - name: Terraform Plan
        shell: bash
        run: |
          cd ${{ matrix.tf_working_dir }}
          terraform plan --parallelism=50 -no-color
